import { library } from '@fortawesome/fontawesome-svg-core'
import { faGithub, faGoogle } from '@fortawesome/free-brands-svg-icons'
import {
    faArrowsRotate,
    faArrowRightFromBracket,
    faBell,
    faBrain,
    faCalendar,
    faChartPie,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleXmark,
    faCode,
    faCube,
    faDatabase,
    faFilter,
    faGear,
    faInfo,
    faLayerGroup,
    faPlus,
    faSort,
    faUser,
    faSearch,
    faChartLine,
    faChartBar,
    faDashboard,
    faBuilding,
    faGlobe,
    faPhone,
    faFax,
    faFolderOpen,
    faHome,
    faFileInvoiceDollar,
    faFileContract,
    faFileLines
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faSearch,
    faFileLines,
    faChartBar,
    faDashboard,
    faChartLine,
    faArrowsRotate,
    faArrowRightFromBracket,
    faBell,
    faBrain,
    faCalendar,
    faChartPie,
    faChevronDown,
    faChevronRight,
    faCircleCheck,
    faCircleXmark,
    faCode,
    faCube,
    faDatabase,
    faFilter,
    faGear,
    faInfo,
    faLayerGroup,
    faPlus,
    faSort,
    faUser,
    faGithub,
    faGoogle,
    faBuilding,
    faGlobe,
    faFax,
    faFolderOpen,
    faHome,
    faFileContract,
    faPhone,
    faFileInvoiceDollar,


)
